/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106292-g242c07982a-20220317"
#endif /* AVUTIL_FFVERSION_H */
